# Generated by Django 5.0.6 on 2024-06-16 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_product_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
